In [2]:

# Example for K = 1 
import sklearn
import numpy as np
class simple_KNN:

    def __init__(self,K=3):
        self.K=1
        
    def fit(self,X,y):
        self.numExemplars = X.shape[0]
        self.numFeatures = X.shape[1]
        self.modelX = X
        self.modelY = y
        
    def predict(self,newItems):
        # read how many  newitems there are
        numToPredict = newItems.shape[0]
        # make an empty 1d array ot hold their predicted labels
        predictions = np.empty((numToPredict,1))
        
        #make a prediction for each one
        for item in range(numToPredict):
            predictions[item] = self.PredictNewItem ( newItems[item])
        
        return predictions
    
    def PredictNewItem(self,newItem):
        
        # Step 1: measure distance to each training item
        distFromNewItem = np.empty((self.numExemplars))
        for exemplar in range (self.numExemplars):
            ## the numpy function calculates the euclidean distance
            distFromNewItem[exemplar] = np.linalg.norm(newItem - self.modelX[exemplar])
  

        # Step 2: find the K closest training example
        closestK = []
        for k in range(self.K):
            # start at begining of array and look for the smallest value
            closest = 0
            for trainingExample in range (0, self.numExemplars):
                if  ( distFromNewItem[trainingExample] < distFromNewItem[closest] ):
                    closest=trainingExample
            # remmber this was the next closest
            closestK.append(closest)
            # set that value yto something huge so it doesn;t get picked again
            distFromNewItem[closest] = 1000000
 
        # step 3: count the votes - agin this is for K=1 and neeeds extending for K>1
        highestLabelPresent = np.max(self.modelY)
        labelCounts = np.zeros( highestLabelPresent+1)
        for k in range(self.K):
            nextClosest = closestK[k]
            nextLabel = self.modelY[nextClosest]
            labelCounts[nextLabel] += 1
        
        mostCommonLabel = 0
        for label in range(highestLabelPresent):
            if ( labelCounts[label] > labelCounts[mostCommonLabel]):
                mostCommonLabel = label
        return mostCommonLabel
    

    
# make train/test split 
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

    
irisX,irisy = load_iris(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(irisX, irisy, test_size=0.33,stratify=irisy)



model = simple_KNN(K=1)
model.fit(X_train,y_train)
ypred = model.predict(X_test)
confusionMatrix = np.zeros((3,3),int)
for i in range(50):
    actual = int(y_test[i])
    predicted = int(ypred[i])
    confusionMatrix[actual][predicted] += 1
print(confusionMatrix)

[[17  0  0]
 [ 2 15  0]
 [16  0  0]]
